p8105_hw1_jt3466
================
Johnstone Tcheou
2024-09-12

# Homework 1

## Problem 1

The `penguins` dataset has already been installed and loaded, named
`penguins`. The `tidyverse` package has also been installed and loaded.
Both the code and output from loading these have been hidden using the
`include=FALSE` option.

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

The penguins dataset has 344 rows and 8 columns, consisting of data on
penguins like species, island, body measurements, sex, and year. The
variables for `species` and `island` are factors, while `bill_length_mm`
and `bill_depth_mm` are doubles, and `flipper_length_mm`, `body_mass_g`,
`sex`, and `year` are integers.

There are 3 different `species`, Adelie, Chinstrap, Gentoo, and 3
different `islands`, Adelie, Chinstrap, Gentoo.

The bill length variable has a min of 32.1 mm and a max of 59.6 mm.
There are 2 observations with `NA`.

The bill depth variable has a min of 13.1 mm and a max of 21.5 mm. There
are 2 observations with `NA`.

The body mass variable has a min of 2700 g and a max of 6300 g. There
are 2 observations with `NA`.

There are 165 female observations and 168 male observations, with 11
observations with `NA`.

The earliest year on record is 2007 while the latest year on record is
2009. The average year is 2008.

The mean flipper length is 200.9152047.

``` r
ggplot(penguins, aes(x=bill_length_mm, y=flipper_length_mm, color=species)) + 
  geom_point()
```

![](p8105_hw1_jt3466_files/figure-gfm/scatterplot-1.png)<!-- -->

``` r
ggsave("scatterplot.pdf")
```

    ## Saving 7 x 5 in image

This is a scatterplot of flipper length in mm against bill length in mm,
with colors corresponding to the species of penguin. There are 2
observations with `NA` for bill and flipper lengths, so the warning that
these observations were removed have been suppressed in this code chunk.

## Problem 2

``` r
q2_df <- tibble(
  rsamp=rnorm(10),
  vec_logical=rsamp>0,
  vec_char=c("This", "vector", "is", "a", "character", "vector", "with", "a", "length", "10"),
  vec_factor=factor(c("easy","medium","hard","medium","medium","easy","hard","hard","easy","medium"))
)

length(pull(q2_df,rsamp))
```

    ## [1] 10

``` r
length(pull(q2_df,vec_char))
```

    ## [1] 10

``` r
length(pull(q2_df,vec_factor))
```

    ## [1] 10

``` r
levels(pull(q2_df,vec_factor))
```

    ## [1] "easy"   "hard"   "medium"

This code creates a dataframe, called `q2_df`, which takes randomly
sampled 10 values from a standard normal distribution, storing it as
`rsamp`, a logical vector of whether the sampled values are greater than
0 called `vec_logical`, a character vector of length 10 called
`vec_char`, a factor vector of length 10 with 3 levels called
`vec_factor`.

The lengths are confirmed when calling the `length()` function on the
vectors and sampled values to confirm they have lengths of 10. Likewise,
the factor is confirmed to have 3 levels when calling the `levels()`
function.

``` r
mean(pull(q2_df, rsamp))
```

    ## [1] 0.02018961

``` r
mean(pull(q2_df, vec_logical))
```

    ## [1] 0.6

``` r
mean(pull(q2_df, vec_char))
```

    ## Warning in mean.default(pull(q2_df, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(q2_df, vec_factor))
```

    ## Warning in mean.default(pull(q2_df, vec_factor)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

Taking the means of the random sample, logical vector, and the factor
vector works.

The random sample is of all numeric values, so the mean of this is
easily calculated, equalling 0.0201896.

The mean of the logical vector works because `TRUE` is numerically 1 and
`FALSE` is numerically 0, so being a random normally distributed
samples, these average out to around 0.5 depending on each random
sample, specifically 0.6.

However, taking the means of the character vector and of the factor
vector does not work, as these are not numeric or logical and cannot be
coerced to numbers for calculating the means of these.

``` r
q2_df %>%
  mutate(
    rsamp=as.numeric(rsamp),
    vec_logical=as.numeric(vec_logical),
    vec_char=as.numeric(vec_char),
    vec_factor=as.numeric(vec_factor)
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `vec_char = as.numeric(vec_char)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

    ## # A tibble: 10 × 4
    ##     rsamp vec_logical vec_char vec_factor
    ##     <dbl>       <dbl>    <dbl>      <dbl>
    ##  1  0.837           1       NA          1
    ##  2  1.14            1       NA          3
    ##  3  0.520           1       NA          2
    ##  4  0.602           1       NA          3
    ##  5 -1.30            0       NA          3
    ##  6 -0.775           0       NA          1
    ##  7  0.403           1       NA          2
    ##  8  0.918           1       NA          2
    ##  9 -1.39            0       NA          1
    ## 10 -0.755           0       10          3

When converting our dataframe variables to numeric, they all work except
for the character vector.

The output retains the random sampling values, coerces the boolean
values to corresponding 1s and 0s, and cannot coerce character values to
numeric. `NA`s are introduced instead, showing why the means cannot be
calculated for these variables that cannot be coerced to numeric
variable type. Since factors naturally have some ordering to the levels,
the values are coerced to the numeric counterparts of their levels.
